import React from 'react';
import { Fahkwang, Roboto } from 'next/font/google';
import './globals.css';

import type { Metadata } from 'next';

import './globals.css';

const fahkwang = Fahkwang({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${fahkwang.className} ${roboto.className}`}>
      <body className='antialiased'>{children}</body>
    </html>
  );
}
