import React from 'react';
import { Fahkwang, Roboto } from 'next/font/google';
import './globals.css';

import type { Metadata } from 'next';

const fahkwang = Fahkwang({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'PC Consulting',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${fahkwang.className} ${roboto.className}`}>
      <body className='antialiased'>{children}</body>
      <link rel='icon' href='/favicon.ico ' type='image/x-icon'></link>
    </html>
  );
}
